wsgi/openshift/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.core.urlresolvers import reverse

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()
from meet.views import UserProfileDetailView, dashboard, home, friends, create_event, event_detail, event_edit, profile, profile_edit, profile_events, user_invite
from api.views import get_friends, invite
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'openshift.views.home', name="home"),
    url(r'^$', home, name="home"),
    # url(r'^openshift/', include('openshift.foo.urls')),
#    url(r'^i$', 'meet.views.accountform', name='accountform'),
    url(r'^accounts/', include('registration.backends.default.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r"^login/$", "django.contrib.auth.views.login",
      {"template_name": "login.html"}, name="login"),
    url(r"^logout/$", "django.contrib.auth.views.logout_then_login", name="logout"),
    # Uncomment the next line to enable the admin:

    #url(r'^users/(?P<slug>[\w.-]+)/$', UserProfileDetailView.as_view(), name="profile"), 
    url(r'^users/(?P<slug>[\w.-]+)/$', profile, name="profile"), 
    url(r'^users/(?P<slug>[\w.-]+)/edit/$', profile_edit, name="profile_edit"), 
    url(r'^users/(?P<slug>[\w.-]+)/events/$', profile_events, name="profile_events"), 
    url(r'^dashboard/$', dashboard, name="dashboard"), 
    url(r'^users/(?P<slug>[\w.-]+)/friends/$', friends, name="friends"), 
    url(r'^events/create/$', create_event, name="create_event"), 
    url(r'^events/(?P<slug>\d+)/$', event_detail, name="event_detail"), 
    url(r'^events/(?P<slug>\d+)/edit/$', event_edit, name="event_edit"), 
    url(r'^invite/(?P<timestamp>\d+)/(?P<request_id>[\w-]+)/$', user_invite, name="user_invite"), 

    #### API #####    
    url(r'^api/friends/$', get_friends, name="get_friends"), 
    url(r'^api/invite/$', invite, name="invite"), 
    
    
    
    url(r'^admin/', include(admin.site.urls)),


)

wsgi/openshift/meet/models.py
from django.db import models
from django import forms
from django.db.models.signals import post_save, post_init
from django.contrib.auth.models import User
from customfunctions import get_timestamp_from_datetime,get_timestamp_from_unix_timestamp , get_current_timestamp #importing custom functions under site dir
import datetime
from django.utils import timezone
from gettext import gettext as _

class UserProfile(models.Model):
  user=models.OneToOneField(User, primary_key=True)
  is_pro=models.BooleanField(default=False)
  city=models.CharField(max_length=50,blank=True)
  country=models.CharField(max_length=50,blank=True)
  image=models.ImageField(upload_to="static/img/u", blank=True)
  twitter=models.CharField(max_length=15, blank=True) 
  facebook=models.CharField(max_length=25, blank=True) 
  foursquare=models.CharField(max_length=25, blank=True) 
  telephone=models.CharField(max_length=15, blank=True) 
  def __unicode__(self):
    #return ' '.join([self.user.first_name,self.user.last_name])
    return str(self.user)
    #return self.user.get_full_name()

  def get_picture(self):
    if (self.image):
      return ''.join(["/",self.image.url])
    else:
      return "/static/img/u/placeholder-user-small.png"
  
  def get_friends(self):
    relationships=Relationship.objects.filter(usr_profile=self)
    friends=[]
    for ship in relationships:
      friends.append(ship.friend)

    return friends

class UserProfileForm(forms.ModelForm):
  first_name = forms.CharField(label=_(u'Firstname'), max_length=30)
  last_name = forms.CharField(label=_(u'Surname'), max_length=30)
  class Meta:
    model = UserProfile
    exclude=['is_pro', 'image']
  def __init__(self, *args, **kwargs):
    print kwargs, args
    super(UserProfileForm, self).__init__(*args, **kwargs)
    self.user= kwargs['instance']
    self.fields['first_name'].initial = self.instance.user.first_name
    self.fields['last_name'].initial = self.instance.user.last_name

    self.fields.keyOrder = ['first_name', 'last_name', 'city', 'country' , 'twitter', 'facebook', 'foursquare', 'telephone' ]
  
  
  def save(self, *args, **kw):
    super(UserProfileForm, self).save(*args, **kw)
    self.instance.user.first_name = self.cleaned_data.get('first_name')
    self.instance.user.last_name = self.cleaned_data.get('last_name')
    self.instance.user.save()
  
def create_user_profile(sender, instance, created, **kwargs):
      if created:
        #Django 1.5 profile, created = UserProfile.object.get_or_create(user=instance)
        UserProfile.objects.create(user=instance)

post_save.connect(create_user_profile, sender=User)

class Event(models.Model):
  BUSINESS="B"
  PERSONAL="P"
  TYPE_MAJOR_CHOICES= (
    (BUSINESS, 'Business'),
    (PERSONAL, 'Personal'),
  )
  OFFICE="OF"
  EXTERNAL="EX"

  SOCIAL="SO"
  ENTERTAINMENT="EN"
  ACTIVITY="AC"

  TYPE_MINOR_CHOICES= (
    (OFFICE,"Office"),
    (EXTERNAL,"External"),
    (SOCIAL,"Social"),
    (ENTERTAINMENT,"Entertainment"),
    (ACTIVITY, "Activity"),
  )

  name = models.CharField(max_length=140)
  version   = models.IntegerField(default=0)
  start_date=models.DateTimeField('start time', default=timezone.now())
  end_date=models.DateTimeField('end time', default=timezone.now)
  type_maj=models.CharField(max_length=1,choices=TYPE_MAJOR_CHOICES,default=PERSONAL)
  type_min=models.CharField(max_length=2,choices=TYPE_MINOR_CHOICES,default=SOCIAL)
  description= models.TextField(blank=True)
  host= models.ForeignKey(UserProfile)
  public=models.BooleanField(default=False)
  def __unicode__(self):
      return ' - '.join([self.name,str(self.start_date), str(self.host)])

class Attendee(models.Model):
  NEEDS_ACTION="N"
  ACCEPTED="A"
  DECLINED="D"
  PARTICIPATION_CHOICES = (
    (ACCEPTED, "Accepted"),
    (DECLINED, "Declined"),
    (NEEDS_ACTION, "Needs-Action"),
  )
  event=models.ForeignKey(Event)
  usr_profile=models.ForeignKey(UserProfile)
  attending=models.CharField(max_length=1,choices=PARTICIPATION_CHOICES, default=NEEDS_ACTION)
  is_public=models.BooleanField(default=False)

  class Meta:
    unique_together = ('event', 'usr_profile',)

  def __unicode__(self):
        return ' - '.join([self.event.name,str(self.usr_profile), self.attending])
  
  def name(self):
    return self.usr_profile.user.get_full_name()

class Message(models.Model):
  usr_profile=models.ForeignKey(UserProfile)
  event=models.ForeignKey(Event)
  pub_date=models.DateTimeField('Published Date')
  contents=models.TextField()
  
  def __unicode__(self):
        return ' - '.join([str(self.usr_profile),str(self.pub_date)])


class Event_Action(models.Model):
  CREATED="CR"
  CANCELLED="CA"
  MOD_DATE="MD"
  MOD_LOCATION="ML"
  CHANGE_HOST="CH"
  PROF_INVITED="IN"
  PROF_ACCEPTED="AC"
  PROF_DECLINED="DE"

  ACTION_EV_CHOICES= (
    (CREATED, "Event Created"),
    (CANCELLED, "Event Cancelled"),
    (MOD_DATE, "Event Date Modified"),
    (MOD_LOCATION, "Event Location Modified"),
    (CHANGE_HOST, "Event Host Changed"),
    (PROF_INVITED, "User Invited"),
    (PROF_ACCEPTED, "User Accepted"),
    (PROF_DECLINED, "User Declined"),  
  )

  event=models.ForeignKey(Event)
  is_Event=models.BooleanField()
  version=models.IntegerField(blank=True)
  action=models.CharField(max_length=2,choices=ACTION_EV_CHOICES) 
  time=models.DateTimeField('Time')
  usr_profile=models.ForeignKey(Attendee)

  def __unicode__(self):
        return ' - '.join([self.event.name,str(self.time), self.action])

class Relationship(models.Model):
  usr_profile=models.ForeignKey(UserProfile)
  friend=models.ForeignKey(UserProfile,related_name='+')
  FRIEND="F"
  FAMILY="Y"
  COLLEAGUE="C"
  ACQUAINTANCE="A"
  CHOICES= (
    (FRIEND, "Friend"),
    (FAMILY, "Family"),
    (COLLEAGUE, "Colleague"),
    (ACQUAINTANCE, "Acquaintance"),
  )
  relationship=models.CharField(max_length=1,choices=CHOICES)
  class Meta:
     unique_together =('usr_profile','friend',)
  def __unicode__(self):
        return ' - '.join([str(self.usr_profile),str(self.friend), self.relationship])

class UserInvite(models.Model):
  request_id=models.CharField(max_length=40, unique=True)
  first_name=models.CharField(max_length=30, blank=True)
  last_name=models.CharField(max_length=30, blank=True)
  email_address=models.CharField(max_length=30, blank=True)
  invite_date=models.PositiveIntegerField(blank=True)
  invited_by=models.ForeignKey(UserProfile, blank=True)
  event_invite=models.ForeignKey(Event, blank=True)
  completed=models.BooleanField(default=False)

  def __unicode__(self):
    return ' - '.join([self.request_id, self.email_address])

def UserInviteInit(sender, instance,  **kwargs):
  instance.invite_date=get_current_timestamp()


post_init.connect(UserInviteInit, sender=UserInvite)

wsgi/openshift/templates/accountform.html
<form action="/contact/" method="post">
    {{ form.as_p }}
        <input type="submit" value="Submit" />
        </form>

wsgi/openshift/templates/base.html
<!DOCTYPE html>
<html style="height:100%;">
  <head>
    <title>MeetApp</title>
    {% block head %}
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/main.css" />
    {% endblock %}
  </head>
  <body style="height:100%;">
    <header>
    {% block header %}
    <h1>MeetApp</h1>
    {% endblock %}
    </header>

    <div class="row-fluid" style="height:80%;background-color:rgb(0, 136, 204);">
      <div class="span2">{% block left-col %}{% endblock %}</div>


      <div class="span8" style="background-color:white;height:100%;">
        <div style="width:95%; margin-left:auto;margin-right:auto;overflow:scroll; height:100%">
          {% if messages %}
          <div>
            {% for message in messages %}
            <div {% if message.tags %} class="alert {{ message.tags }}"{% endif %}> <button type="button" class="close" data-dismiss="alert">&times;</button>{{ message }}</div>
            {% endfor %}
          </div>
          {% endif %}
          {% block content %}{% endblock %}
        </div>
      </div>
      <div class="span2">{% block right-col %}{% endblock %}</div>


    </div>


    <footer>
    <p>
    <a href="{% url home %}">Home</a> |
    {% if user.is_authenticated %}
    <a href="{% url logout %}">Logout</a> |
    <a href="{% url profile slug=user.username %}"><b>{{ user.username }}</b></a> 
    {% else %}
    <a href="{% url login %}">Login</a> | 
    <a href="{% url registration_register %}">Sign Up</a> 
    {% endif %}
    </p>
    </footer>
  </body>
</html>

wsgi/openshift/templates/create_event.html
{% extends "header.html" %}

{% block content %}
<h2>Create a new meet</h2>
{% if form.errors %}
<p style="color: red;">
Please correct the error{{ form.errors|pluralize }} below.
</p>
{% endif %}

<form action="" method="post">
  <table>
    {{ form }}
  </table>
  {% csrf_token %}
  <input type="submit" value="Submit">
</form>

{% endblock %}

wsgi/openshift/templates/dashboard.html
{% extends "header.html" %}




{% block content %}
{% if user.first_name == "" %}
<div class="alert alert-error">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <p>Please add your first and last name so people know who you are!</p>
</div>{% endif %}
<h2>My meets</h2>
{% if events %}
{% for event in events %}
<div class="well">
  <div style="float:left;"><a href="{% url event_detail slug=event.id %}"><h3>{{ event.name }}</h3></a></div>
  <div style="float:right;"><span class="label label-success">Time until: {{event.start_date|timeuntil }}</span></div>
  <div style="clear:both;"></div>
  <div class="row-fluid">
    <div class="span10">
      {% ifequal event.start_date.date  event.end_date.date%}

      <p><strong>Date:</strong> {{ event.start_date.date }} </p>
      <p><strong>Time:</strong> {{ event.start_date.time }} - {{ event.end_date.time }} </p>
      {% else %}
      <p><strong>Start Date:</strong> {{ event.start_date }}</p>
      <p><strong>End Date:</strong> {{ event.end_date }}</p>
      <p><strong>Duration: Duration</strong></p>
      {% endifequal %}

      <strong>Description:</strong><br><br>
      <p class="well" style="background-color:white;">{{ event.description }}</p>
    </div><!-- /span8 -->
    <div class="span2">
      <h4> Host:</h4>
      <a href="{% url profile slug=event.host.user.username %}" class="text-center" ><img style="margin-left:auto;margin-right:auto;width:90%;" src="{{ event.host.get_picture }}" /></a>
      <a href="{% url profile slug=event.host.user.username %}" class="text-center" ><h5>{{event.host}}<h5></a>
        </div>
      </div> <!-- /row-fluid -->
    </div> <!-- /well -->
    {% endfor %}


  </div>
  {% else %}
  <div class="hero-unit">
    <h1>You have no meets :(</h1>
    <p>Don't worry, you can always create a new one!</p>
    <p>
    <a class="btn btn-primary btn-large" href="{% url create_event %}">
      Create meet
    </a>
    </p>
  </div>
  {% endif %}
  {% endblock %}

wsgi/openshift/templates/edit_profile.html
{% extends "header.html" %}

{% block content %}
<h2>{{ user.username }}'s Profile</h2>

<form method="post" action="">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Edit">
</form>

{% endblock %}

wsgi/openshift/templates/event_detail.html
{% extends "header.html" %}

{% block head2 %}
<script src="{{ STATIC_URL }}js/jquery.cookie.js" type="text/javascript"></script>
<script type="text/javascript">var event_id="{{ event.id }}";</script>
<script src="{{ STATIC_URL }}js/json2.js" type="text/javascript"></script>
<script src="{{ STATIC_URL }}js/friends.js" type="text/javascript"></script>
<script src="{{ STATIC_URL }}js/jquery.tagsinput.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/jquery.tagsinput.css" />
{% endblock %}


{% block content %}
<div class="well">
  <div style="float:left;"><h3>{{ event.name }}</h3></div>
  <div style="float:right;"><span class="label label-success">Time until: {{event.start_date|timeuntil }}</span></div>
  <div style="clear:both;"></div>
  <hr>
  <div class="row-fluid">
    <div class="span10">
      {% ifequal event.start_date.date  event.end_date.date%}

      <p><strong>Date:</strong> {{ event.start_date.date }} </p>
      <p><strong>Time:</strong> {{ event.start_date.time }} - {{ event.end_date.time }} </p>
      {% else %}
      <p><strong>Start Date:</strong> {{ event.start_date }}</p>
      <p><strong>End Date:</strong> {{ event.end_date }}</p>
      <p><strong>Duration: Duration</strong></p>
      {% endifequal %}

      <strong>Description:</strong><br><br>
      <p class="well" style="background-color:white;">{{ event.description }}</p>
    </div><!-- /span8 -->
    <div class="span2">
      <h4> Host:</h4>
      <a href="{% url profile slug=event.host.user.username %}" class="text-center" ><img style="margin-left:auto;margin-right:auto;width:90%;" src="{{ event.host.get_picture }}" /></a>
      <a href="{% url profile slug=event.host.user.username %}" class="text-center" ><h5>{{event.host}}<h5></a>
        </div>
      </div> <!-- /row-fluid -->
      {% if personal_att %}
      <div class="personal">
        <p class="inline">I have:</p><div class="
          tn-group"><button class="btn btn-default">{{ personal_att.get_attending_display }}</button>
          <button class="btn dropdown-toggle" data-toggle="dropdown">
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
            <!-- dropdown menu links -->
            <li><a href="">Accepted</a></li>
            <li><a href="">Declined</a></li>
          </ul>
        </div>
        <a href="{% url event_edit slug=event.id %}" class="btn btn-primary">Edit event</a>
        <a href="#myModal" role="button" class="btn btn-primary" data-toggle="modal">Invite friends</a>
      </div><br>
      <div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h3 id="myModalLabel">Invite Friends</h3>
        </div>
        <div class="modal-body">
          <div id="friend-list">
          </div>
          <hr>
          <div id="new_friend">
            <div class="input-append">
            <input type="text" class="span12" id="new-invitee" placeholder="invite.me@example.com" > <button id="new-invitee-btn" class="btn" type="button" id="btn-new-invitee">Send invite</button>
          </div>
          <span class="help-block">Separate email addresses with semicolons</span>
         
          </div>
        </div>
        <div class="modal-footer">
          <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
          <button id="invite-button" data-dismiss="modal" class="btn btn-primary"><i class="icon-envelope icon-white"></i> Invite</button>
        </div>
      </div>
      {% endif %}
      <div class="tabbable"> <!-- Only required for left/right tabs -->
        <ul class="nav nav-tabs">
          <li class="active"><a href="#tab1" data-toggle="tab">Event Messages</a></li>
          <li><a href="#tab2" data-toggle="tab">Attendees ({{ event.attendee_set.all.count }})</a></li>
        </ul>
        <div class="tab-content">
          <div class="tab-pane active" id="tab1">
            {% if event.message_set.all %}
            {% for msg in event.message_set.all %}
            <div class="media fluid-row msg">
              <div class="span1">
                <a class="pull-left"  style="width:99%" href="#">
                  <img class="media-object" style="width:inherit;" src="{{ msg.usr_profile.get_picture }}">
                </a>
              </div>
              <div class="media-body span11">
                <!-- <h4 class="media-heading">Media heading</h4>-->
                <p><a href=""><b>{{ msg.usr_profile.user.get_full_name }}</b></a>: {{msg.contents}}</p>

                <!-- Nested media object -->
              </div>
              <div class="clearfix"></div>
            </div>

            {% endfor %}
            {% else %}
            <h2>No messages</h2>
            {% endif %}
            <hr><br>
            <form method="POST">
              <input name="contents" type="text" class="input-block-level" placeholder="Say something…" />
              {% csrf_token %}
              <button type="submit" class="btn pull-right">Send</button>
            </form>


          </div>
          <div class="tab-pane" id="tab2">

            {% for attendee in event.attendee_set.all %}
            <div class="attendee">
              <a href="{% url profile slug=attendee.usr_profile.user.username %}"><img style="margin-left:5%;margin-right:5%;width:20%;" class="pull-left" src="{{ attendee.usr_profile.get_picture }}" /></a>
              <a href="{% url profile slug=attendee.usr_profile.user.username %}"><h3 class="pull-left" style="margin-bottom:2px; width:auto;">{{ attendee.name }}</h3></a><br><br><br>
              {% if attendee.attending == "D" %}
              <span class="badge badge-important">declined</span>
              {% elif attendee.attending == "A" %}
              <span class="badge badge-success">attending</span>
              {% else %}  
              <span class="badge badge-warning">no reply</span>
              {% endif %}
              <div class="clearfix"></div>
            </div>
            {% endfor %}

          </div>
        </div>
      </div>




    </div> <!-- /well -->


    {% endblock %}

wsgi/openshift/templates/event_edit.html
{% extends "header.html" %}




{% block content %}

<div class="well">
  <div style="float:left;"><h3>{{ event.name }}</h3></div>
  <div style="float:right;"><span class="label label-success">Time until: {{event.start_date|timeuntil }}</span></div>
  <div style="clear:both;"></div>
  <hr>
  <div class="row-fluid">
    <div class="span10">
      {% ifequal event.start_date.date  event.end_date.date%}

      <p><strong>Date:</strong> {{ event.start_date.date }} </p>
      <p><strong>Time:</strong> {{ event.start_date.time }} - {{ event.end_date.time }} </p>
      {% else %}
      <p><strong>Start Date:</strong> {{ event.start_date }}</p>
      <p><strong>End Date:</strong> {{ event.end_date }}</p>
      <p><strong>Duration: Duration</strong></p>
      {% endifequal %}

      <strong>Description:</strong><br><br>
      <p class="well" style="background-color:white;">{{ event.description }}</p>
    </div><!-- /span8 -->
    <div class="span2">
      <h4> Host:</h4>
      <a href="{% url profile slug=event.host.user.username %}" class="text-center" ><img style="margin-left:auto;margin-right:auto;width:90%;" src="{{ event.host.get_picture }}" /></a>
      <a href="{% url profile slug=event.host.user.username %}" class="text-center" ><h5>{{event.host}}<h5></a>
        </div>
      </div> <!-- /row-fluid -->
      {% if personal_att %}
      <div class="personal">
        <p class="inline">I have:</p><div class="btn-group"><button class="btn btn-default">{{ personal_att.get_attending_display }}</button>
          <button class="btn dropdown-toggle" data-toggle="dropdown">
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
            <!-- dropdown menu links -->
            <li><a href="">Accepted</a></li>
            <li><a href="">Declined</a></li>
          </ul>
        </div><a href="{% url event_detail slug=event.id %}" class="btn btn-large btn-primary">Un-edit event</a>
      </div><br>
      {% endif %}
      <div class="tabbable"> <!-- Only required for left/right tabs -->
        <ul class="nav nav-tabs">
          <li class="active"><a href="#tab1" data-toggle="tab">Event Messages</a></li>
          <li><a href="#tab2" data-toggle="tab">Attendees ({{ event.attendee_set.all.count }})</a></li>
        </ul>
        <div class="tab-content">
          <div class="tab-pane active" id="tab1">
            {% if event.message_set.all %}
            {% for msg in event.message_set.all %}
            <div class="media fluid-row msg">
              <div class="span1">
              <a class="pull-left"  style="width:99%" href="#">
                <img class="media-object" style="width:inherit;" src="{{ msg.usr_profile.get_picture }}">
              </a>
            </div>
              <div class="media-body span11">
                <!-- <h4 class="media-heading">Media heading</h4>-->
                <p><a href=""><b>{{ msg.usr_profile.user.get_full_name }}</b></a>: {{msg.contents}}</p>

                <!-- Nested media object -->
              </div>
            <div class="clearfix"></div>
          </div>

          {% endfor %}
          {% else %}
          <h2>No messages</h2>
          {% endif %}
          <hr><br>
          <form method="POST">
            <input name="contents" type="text" class="input-block-level" placeholder="Say something…" />
             {% csrf_token %}
             <button type="submit" class="btn pull-right">Send</button>
           </form>


          </div>
          <div class="tab-pane" id="tab2">
            <p>Howdy, I'm in Section 2.</p>

            {% for attendee in event.attendee_set.all %}
            <div class="attendee">
              <a href="{% url profile slug=attendee.usr_profile.user.username %}"><img style="margin-left:5%;margin-right:5%;width:20%;" class="pull-left" src="{{ attendee.usr_profile.get_picture }}" /></a>
              <a href="{% url profile slug=attendee.usr_profile.user.username %}"><h3 class="pull-left" style="margin-bottom:2px; width:auto;">{{ attendee.name }}</h3></a><br><br><br>
              {% if attendee.attending == "D" %}
              <span class="badge badge-important">declined</span>
              {% elif attendee.attending == "A" %}
              <span class="badge badge-success">attending</span>
              {% else %}  
              <span class="badge badge-warning">no reply</span>
              {% endif %}
              <div class="clearfix"></div>
            </div>
            {% endfor %}

          </div>
        </div>
      </div>




    </div> <!-- /well -->


    {% endblock %}

wsgi/openshift/templates/friends.html
{% extends "header.html" %}

{% block content %}
<h2>{{ user.username }}'s friends</h2>
{% if object.userprofile.image %}
{% endif %}
<div>
  <ul class="nav nav-pills">
    <li><a href="{% url profile slug=user.username %}">profile</a></li>
    <li class="active"><a href="#">friends</a></li>
    <li><a href="{% url profile_events slug=user.username %}">meets</a></li>
  </ul>
</div>
{% if friends %}
{% for friend in friends %}
<div class="well pull-left" style="width:40%; margin:2%;">
  <div class="pull-left" style="width:30%;"><a href="{% url profile slug=friend.user.username %}" > <img  src="{{ friend.get_picture }}" /> </a>
  </div>
  <div class="profile-info pull-right" style="width:65%;">
    <a href="{% url profile slug=friend.user.username %}" > <h3 style="margin:0;">{{ friend.user.get_full_name}}</h3></a>
    <table style="border-collapse: separate; border-spacing: 8px;">
      <tr><td><b>City</b></td><td>{{ friend.city }}</td></tr>
      <tr><td><b>Country</b></td><td>{{ friend.country }}</td></tr>
    </table>
  </div>

</div>

{% endfor %}
{% else %}
<div class="hero-unit">
  <h1>This user currently has no friends :(</h1>
  <p> Become their friend today!</p>
  <a href="#" class="btn btn-primary disabled">Submit friend request</a>
</div>
{% endif %}
{% endblock %}

wsgi/openshift/templates/header.html
{% extends "base.html" %}


{% block head %}

<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/meet.css" />
<link type="text/css" href="{{ STATIC_URL }}css/jquery-ui-1.10.3.custom.css" rel="Stylesheet" />
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" type="text/javascript"></script> 
<script src="{{ STATIC_URL }}js/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
<script src="{{ STATIC_URL }}bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
{% block head2 %}

{% endblock %}
{% endblock %}



{% block header %}
<div class="row-fluid">
  <div class="span2"></div>

  <div class="span8">

    <div class="row-fluid">

      <div class="span4"></div>
      <div class="span4"><h1 class="text-center">MeetApp</h1></div>
      <div class="span4 valign" style="min-height:4em;">
        <ul class="inline valign">
          {% if user.is_authenticated %}
          <li class="valign"><div class="valign"><a href="{% url dashboard %}">Dashboard</a></div></li>
          <li class="valign"><a href="{% url profile slug=user.username %}">Profile</a></li>
          <li class="valign"><a href="{% url friends slug=user.username %}">Friends</a></li>
          {% else %}
          <li class="valign"><a href="{% url registration_register %}">Sign Up</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
  </div>

  <div class="span2"></div>
</div>

{% endblock %}